# Generated by Django 3.2.5 on 2021-07-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sinbike_Customers', '0012_alter_customer_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('vendor', models.CharField(default='others', max_length=128)),
                ('reserved_by', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinbike_Bikes.bike')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinbike_Customers.customer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
