# Generated by Django 3.2.5 on 2021-07-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinbike_Customers', '0012_alter_customer_avatar'),
        ('sinbike_Bikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='bike_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='bike',
            name='reserved_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sinbike_Customers.customer'),
        ),
    ]
