# Generated by Django 3.2.5 on 2021-07-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinbike_Customers', '0012_alter_customer_avatar'),
        ('sinbike_Bikes', '0002_auto_20210718_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='reserved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sinbike_Customers.customer'),
        ),
    ]
