# Generated by Django 3.2.5 on 2021-07-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinbike_Bikes', '0005_merge_20210728_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
