# Generated by Django 3.2.5 on 2021-07-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinbike_Customers', '0004_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created',
            new_name='created_at',
        ),
    ]
