# Generated by Django 3.2.5 on 2021-07-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinbike_Customers', '0005_auto_20210712_1847'),
    ]

    operations = [
    ]
