# Generated by Django 3.2.5 on 2021-07-17 19:00

from django.db import migrations, models
import sinbike_Customers.models


class Migration(migrations.Migration):

    dependencies = [
        ('sinbike_Customers', '0009_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='', upload_to=sinbike_Customers.models.gen_avatar_upload_location),
        ),
    ]
