# Generated by Django 3.2.5 on 2021-07-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinbike_Customers', '0014_auto_20210728_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
