# Generated by Django 3.2.5 on 2021-08-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinbike_Customers', '0017_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='attachments',
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(upload_to='reports/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinbike_Customers.report')),
            ],
        ),
    ]
